services:
  meal-order-backend:
    build:
      context: ./mup-vehicles
      dockerfile: Dockerfile
    image: meal-order-backend:latest
    ports:
      - ${PROJECT_SERVER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
      - mongo

  server-service:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    image: server-service:latest
    ports:
      - ${SERVER_SERVICE_PORT}
    depends_on:
      - db
      - mongo

  traffic-police-service:
    build:
      context: ./traffic-police
      dockerfile: Dockerfile
    image: traffic-police-service:latest
    ports:
      - ${TRAFFIC_POLICE_SERVICE_PORT}
    depends_on:
      - db
      - mongo

  vehicles-service:   # <-- proveri da li je ovo zapravo mup-vehicles
    build:
      context: ./mup-vehicles
      dockerfile: Dockerfile
    image: vehicles-service:latest
    ports:
      - ${VEHICLES_SERVICE_PORT}
    depends_on:
      - db
      - mongo

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_DB_PORT}

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_DB_PORT}
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
